### PR TITLE
Missing semicolon in documentation

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
This one tripped me up! As solved here https://forum.getkirby.com/t/issue-configuring-patterns-with-preview-value/4172/2?u=paulrobertlloyd

### CODE REVIEW

**Comment by jdvivar** [comment]
+1

**Comment by paulrobertlloyd** [comment]
Pinging @bastianallgeier! Would be great if you could accept this tiny correction to the docs, if only so I can remove my fork. Thanks!

**Comment by lukasbestle** [comment]
Sorry for the delay!

**Comment by paulrobertlloyd** [comment]
Thanks @lukasbestle!

**Pull request merged**
